name:                shop-example
version:             0.1.0.0
github:              "githubuser/shop-example"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/shop-example#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- blaze-markup
- bytestring
- containers
- http-api-data
- http-media
- mtl
- monad-logger
- persistent
- relude
- resource-pool
- servant
- servant-auth
- servant-auth-server
- servant-blaze
- servant-server
- shakespeare
- text
- unliftio-core
- wai
- warp

default-extensions:
- NoImplicitPrelude

# Syntactic additions
- BlockArguments
- DerivingStrategies
- InstanceSigs
- LambdaCase
- OverloadedRecordDot
- PartialTypeSignatures
- StandaloneDeriving
- StandaloneKindSignatures
- TypeApplications

# Extended features
- MultiParamTypeClasses
- DeriveGeneric
- GADTs
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables

# Type-level operations
- ConstraintKinds
- DataKinds
- TypeFamilies
- TypeOperators

# TH and QuasiQuotation
- TemplateHaskell
- QuasiQuotes

# Not fully stable features
- FlexibleContexts

ghc-options:
- -Wall
- -Wcompat
- -Wextra
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-partial-type-signatures
- -fshow-warning-groups
- -pgmL markdown-unlit

build-tools:
- markdown-unlit

library:
  source-dirs: src

executables:
  shop-example-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - shop-example
    - persistent-mysql

tests:
  shop-example-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - shop-example
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
